-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 23:04:00 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso` (
  `idCurso` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `HorasDuracao` INT(11) NOT NULL,
  PRIMARY KEY (`idCurso`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno` (
  `idAluno` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Matricula` INT(11) NOT NULL,
  `SemestreAtual` INT(11) NOT NULL,
  `Idade` INT(11) NULL DEFAULT NULL,
  `Curso_idCurso` INT(11) NOT NULL,
  PRIMARY KEY (`idAluno`, `Curso_idCurso`),
  UNIQUE INDEX `Matricula_UNIQUE` (`Matricula` ASC),
  INDEX `fk_Aluno_Curso1_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_Aluno_Curso1`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`materia` (
  `idMateria` INT(11) NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `NumAulas` INT(11) NOT NULL,
  PRIMARY KEY (`idMateria`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`aluno_has_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`aluno_has_materia` (
  `Aluno_idAluno` INT(11) NOT NULL,
  `Materia_idMateria` INT(11) NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`, `Materia_idMateria`),
  INDEX `fk_Aluno_has_Materia_Materia1_idx` (`Materia_idMateria` ASC),
  INDEX `fk_Aluno_has_Materia_Aluno1_idx` (`Aluno_idAluno` ASC),
  CONSTRAINT `fk_Aluno_has_Materia_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`curso_has_materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`curso_has_materia` (
  `Curso_idCurso` INT(11) NOT NULL,
  `Materia_idMateria` INT(11) NOT NULL,
  PRIMARY KEY (`Curso_idCurso`, `Materia_idMateria`),
  INDEX `fk_Curso_has_Materia_Materia1_idx` (`Materia_idMateria` ASC),
  INDEX `fk_Curso_has_Materia_Curso_idx` (`Curso_idCurso` ASC),
  CONSTRAINT `fk_Curso_has_Materia_Curso`
    FOREIGN KEY (`Curso_idCurso`)
    REFERENCES `mydb`.`curso` (`idCurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Curso_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`nota` (
  `idNota` INT(11) NOT NULL AUTO_INCREMENT,
  `NP1` INT(11) NOT NULL,
  `NP2` INT(11) NOT NULL,
  `NP3` INT(11) NULL DEFAULT NULL,
  `NF` INT(11) NULL DEFAULT NULL,
  `Situacao` INT(11) NULL DEFAULT NULL,
  `Aluno_idAluno` INT(11) NOT NULL,
  `Materia_idMateria` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idNota`),
  INDEX `fk_Nota_Aluno1_idx` (`Aluno_idAluno` ASC),
  INDEX `Materia_idMateria` (`Materia_idMateria` ASC),
  CONSTRAINT `fk_Nota_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `mydb`.`aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nota_ibfk_1`
    FOREIGN KEY (`Materia_idMateria`)
    REFERENCES `mydb`.`materia` (`idMateria`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
